{
 "title": "API Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "HTTP average duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(http_requests_milliseconds_sum[5m])) / sum by (endpoint) (rate(http_requests_milliseconds_count[5m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Calculator Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(errors_calculator_total[5m])"
    }
   ]
  },
  {
   "title": "HTTP requests per route",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(http_requests_total[5m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Last Values",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_sum1n" },
    { "expr": "last_fibo" },
    { "expr": "list_size" },
    { "expr": "last_calculator" }
   ]
  }
 ]
}